/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.KhoBUS;
import BUS.LoaiSPBUS;
import BUS.SanPhamBUS;
import DAO.KhoDAO;
import DTO.Kho;
import DTO.LoaiSP;
import DTO.SanPham;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import jxl.write.Formula;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;
import jxl.write.biff.RowsExceededException;

/**
 *
 * @author DELL
 */
public class KhoForm extends javax.swing.JDialog {
    DefaultTableModel model;
    KhoBUS bus;
    /**
     * Creates new form KhoForm
     */
    private HomeForm home;
    public KhoForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        home=(HomeForm) parent;
        bus=new KhoBUS();
        bus.DocKho();
        model =(DefaultTableModel)tbl.getModel();
        bus.showTable(model);
        loadMaSP();
    }
    
    public void loadMaSP(){
        DefaultComboBoxModel mdsp=new DefaultComboBoxModel();
        SanPhamBUS bus=new SanPhamBUS();
        bus.DocSP();
        for(SanPham sp: SanPhamBUS.lssp)
            mdsp.addElement(sp.getMaSP());
        cmbMaSP.setModel(mdsp);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        txtNgay = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtTimKiem = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLoadDL = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtGiaXuat = new javax.swing.JTextField();
        btnXuatEX = new javax.swing.JButton();
        btnDocEX = new javax.swing.JButton();
        cmbMaSP = new javax.swing.JComboBox<>();
        txtMaLoai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Mã Loại", "Ngày nhập", "Giá/1 cái", "Giá xuất", "Số lượng"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("KHO");

        jLabel4.setText("Mã SP");

        jLabel5.setText("Tên SP");

        jLabel6.setText("Ngày nhập");

        jLabel7.setText("Số lượng");

        jLabel8.setText("Tìm kiếm ");

        txtTenSP.setEditable(false);

        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimKiemMouseClicked(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Modify.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLoadDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Undo.png"))); // NOI18N
        btnLoadDL.setText("Load Dữ Liệu");
        btnLoadDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDLActionPerformed(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Find.png"))); // NOI18N
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel9.setText("Đơn giá");

        txtDonGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDonGiaKeyPressed(evt);
            }
        });

        jLabel10.setText("Mã Loại");

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.png"))); // NOI18N
        btn1.setText("Quay lại");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Giá Xuất");

        txtGiaXuat.setEditable(false);

        btnXuatEX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/List.png"))); // NOI18N
        btnXuatEX.setText("Xuất ra file Excel");
        btnXuatEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatEXActionPerformed(evt);
            }
        });

        btnDocEX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Folder.png"))); // NOI18N
        btnDocEX.setText("Đọc từ file Excel");
        btnDocEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocEXActionPerformed(evt);
            }
        });

        cmbMaSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMaSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbMaSPFocusLost(evt);
            }
        });

        txtMaLoai.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(cmbMaSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnLoadDL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addComponent(txtGiaXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(txtMaLoai))))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDocEX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXuatEX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn1)
                .addGap(25, 25, 25))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDonGia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE))
                            .addComponent(txtMaLoai)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                            .addComponent(cmbMaSP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGiaXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLoadDL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatEX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDocEX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDLActionPerformed
        model.setRowCount(0);
        bus.showTable(model);
        txtTimKiem.setText("");
    }//GEN-LAST:event_btnLoadDLActionPerformed
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        Kho s = new Kho();
        KhoBUS bus=new KhoBUS();
        boolean check=true;
        
        SanPhamBUS sp=new SanPhamBUS();
        sp.DocSP();
        
        String ma=cmbMaSP.getSelectedItem().toString();
        String ten=txtTenSP.getText();
        if(!bus.KiemTraTrungMaSP(ma)){
            check=false;
            JOptionPane.showMessageDialog(rootPane, "Trùng  Mã SP rồi mẹ");
        }
        if(sp.KiemTraTrungMaSP(ma)==true && sp.KiemTraTrungTenSP(ten)==true){
            check=false;
            JOptionPane.showMessageDialog(rootPane, "Mã SP hoặc Tên SP ko tồn tại");
        }
        s.setMaSP(ma);
        s.setTenSP(ten);
        
        try {
            s.setNgayNhap(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgay.getText()));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Sai định dạng ngày,\n Định dạng:dd/MM/yyyy");
            txtNgay.requestFocus();
            check=false;
        }
        
        String gia=txtDonGia.getText();
        try {
            Integer.parseInt(gia);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Gía phải là số nguyên");
            txtDonGia.requestFocus();
            check=false;
        }
        s.setDongia(gia.toString());
        
        String sl=txtSoLuong.getText();
        try {
            Integer.parseInt(sl);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số nguyên");
            txtSoLuong.requestFocus();
            check=false;
        }
        s.setSl(sl.toString());
        s.setMaLoai(txtMaLoai.getText());
        s.setGiaxuat(txtGiaXuat.getText());
        

        if(check==true){
            try {
                if(bus.ThemSP(s)==true){
                    bus.showResult(model);
                    JOptionPane.showMessageDialog(rootPane, "Thêm SP thành công!");

                    txtTenSP.setText("");
                    txtNgay.setText("");
                    txtDonGia.setText("");
                    txtGiaXuat.setText("");
                    txtSoLuong.setText("");
                    txtMaLoai.setText("");
                } 
            } catch (SQLException ex) {
                Logger.getLogger(Kho.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Thêm không thành cong ! Chắc là sai 1 chỗ gì đó rầu");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row=tbl.getSelectedRow();
        boolean check1=true;
        if(row == -1){
            JOptionPane.showMessageDialog(rootPane, "Chọn dòng để sủa");
            check1=false;
        }
        if(check1==true){
            Kho std = bus.lsk.get(row);
            if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    bus.xoavitrids(row);
                    bus.XoaSP(std);

                    txtTenSP.setText("");
                    txtNgay.setText("");
                    txtGiaXuat.setText("");
                    cmbMaSP.setEnabled(true);
                    txtDonGia.setText("");
                    txtSoLuong.setText("");
                    txtMaLoai.setText("");
                } catch (SQLException ex) {
                    Logger.getLogger(Kho.class.getName()).log(Level.SEVERE, null, ex);
                }
                model.removeRow(row);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Lần sau nghĩ kỹ r hãy ấn nha mạy !!!");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        Kho s = new Kho();
        boolean check=true;
       
        int row=tbl.getSelectedRow();
        boolean check1=true;
        if(row == -1){
            JOptionPane.showMessageDialog(rootPane, "Chọn dòng để sủa");
            check1=false;
        }
        if(check1==true){
            SanPhamBUS sp=new SanPhamBUS();
            sp.DocSP();
                       
            s.setMaSP(cmbMaSP.getSelectedItem().toString());
            s.setTenSP(txtTenSP.getText());

            try {
                s.setNgayNhap(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgay.getText()));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Sai định dạng ngày,\n Định dạng:dd/MM/yyyy");
                txtNgay.requestFocus();
                check=false;
            }
            
            String gia=txtDonGia.getText();
            try {
                Integer.parseInt(gia);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Gía phải là số nguyên");
                txtDonGia.requestFocus();
                check=false;
            }
            s.setDongia(gia.toString());

            String sl=txtSoLuong.getText();
            try {
                Integer.parseInt(sl);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số nguyên");
                txtSoLuong.requestFocus();
                check=false;
            }
            s.setSl(sl.toString());

            s.setMaLoai(txtMaLoai.getText());
            s.setGiaxuat(txtGiaXuat.getText());

            if(check==true){
                try {
                    if(bus.SuaSP(s)==true){
                        model.setRowCount(0);
                        bus.DocKho();
                        bus.showTable(model);

                        txtTenSP.setText("");
                        txtNgay.setText("");
                        txtDonGia.setText("");
                        cmbMaSP.setEnabled(true);
                        txtSoLuong.setText("");
                        txtGiaXuat.setText("");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Kho.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, "Edit thất bại");
                }

            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String b=txtTimKiem.getText();
        boolean check=false;
        for(int i=0;i<bus.lsk.size();i++){
            if(bus.lsk.get(i).getMaSP().toLowerCase().equals(b.toLowerCase())){
                check=true;
                model.setRowCount(0);
                model.addRow(new Object[]{
                    bus.lsk.get(i).getMaSP(), bus.lsk.get(i).getTenSP(), bus.lsk.get(i).getMaLoai(), bus.lsk.get(i).getNgayNhap(), bus.lsk.get(i).getDongia(),bus.lsk.get(i).getGiaxuat(),bus.lsk.get(i).getSl()
                });
                break;
            }
            else if(bus.lsk.get(i).getTenSP().toLowerCase().equals(b.toLowerCase())){
                check=true;
                model.setRowCount(0);
                model.addRow(new Object[]{
                     bus.lsk.get(i).getMaSP(), bus.lsk.get(i).getTenSP(), bus.lsk.get(i).getMaLoai(), bus.lsk.get(i).getNgayNhap(), bus.lsk.get(i).getDongia(),bus.lsk.get(i).getGiaxuat(),bus.lsk.get(i).getSl()
                });
                break;
            }
        }
        if(check==false){
            JOptionPane.showMessageDialog(rootPane, "Không có MãSP hay TênSP trong bảng nhóe !");
            model.setRowCount(0);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int row=tbl.getSelectedRow();
        cmbMaSP.setSelectedItem(tbl.getModel().getValueAt(row, 0).toString());
        cmbMaSP.setEnabled(false);
        txtTenSP.setText(tbl.getModel().getValueAt(row, 1).toString());
        txtMaLoai.setText(tbl.getModel().getValueAt(row, 2).toString());
        txtNgay.setText(tbl.getModel().getValueAt(row, 3).toString());
        txtDonGia.setText(tbl.getModel().getValueAt(row, 4).toString());
        txtGiaXuat.setText(tbl.getModel().getValueAt(row, 5).toString());
        txtSoLuong.setText(tbl.getModel().getValueAt(row, 6).toString());
    }//GEN-LAST:event_tblMouseClicked

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        this.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_btn1ActionPerformed

    private void txtTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMouseClicked
        cmbMaSP.setEnabled(true);
        txtTenSP.setText("");
        txtNgay.setText("");
        txtDonGia.setText("");
        txtSoLuong.setText("");
        txtMaLoai.setText("");
        txtGiaXuat.setText("");
    }//GEN-LAST:event_txtTimKiemMouseClicked

    private void txtDonGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDonGiaKeyPressed
        float giaxuat;
        String gia=txtDonGia.getText();
               
        try {
            giaxuat = Float.parseFloat(gia) * (1+ (float)0.1);
        
            if (evt.getKeyCode()==KeyEvent.VK_ENTER){
                txtGiaXuat.setText(Float.toString(giaxuat));
            }
        } catch (java.lang.NumberFormatException ex){
            
        }
    }//GEN-LAST:event_txtDonGiaKeyPressed

    private void btnXuatEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatEXActionPerformed
        WritableWorkbook wordbook;
        
        try{
            wordbook = Workbook.createWorkbook(new File("kho.xls"));
            WritableSheet sheet=wordbook.createSheet("kho", 0);
            
            sheet.addCell(new Label(0,0,"Mã SP"));
            sheet.addCell(new Label(1,0,"Tên SP"));
            sheet.addCell(new Label(2,0,"Mã Loại"));
            sheet.addCell(new Label(3,0,"Ngày nhập"));
            sheet.addCell(new Label(4,0,"Giá 1 cái"));
            sheet.addCell(new Label(5,0,"Giá Xuất"));
            sheet.addCell(new Label(6,0,"Số lượng"));
            int row=1;
            for(Kho kh : KhoBUS.lsk){
                sheet.addCell(new Label(0,row,kh.getMaSP()));
                sheet.addCell(new Label(1,row,kh.getTenSP()));
                sheet.addCell(new Label(2,row,kh.getMaLoai()));
                sheet.addCell(new Label(3,row,kh.getNgayNhap().toString()));
                sheet.addCell(new Label(4,row,kh.getDongia()));
                sheet.addCell(new Label(5,row,kh.getGiaxuat()));
                sheet.addCell(new Label(6,row++,kh.getSl()));
            }
            
            wordbook.write();
            wordbook.close();
            JOptionPane.showMessageDialog(null,"Xuất thành công");
        } catch (IOException ex) {
            Logger.getLogger(Kho.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(Kho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXuatEXActionPerformed

    private void btnDocEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocEXActionPerformed
        model.setRowCount(0);
        Workbook wordbook;
        dangdocfile=1;
        JFileChooser jc=new JFileChooser();
        int vv=jc.showOpenDialog(jLabel4);
        if(vv==0){
            File link=jc.getSelectedFile();
            try{
                wordbook=Workbook.getWorkbook(link);
                Sheet sheet=wordbook.getSheet(0);
                int row=sheet.getRows();
                int col=sheet.getColumns();
                
                for(int i=1;i<row;++i){
                    Vector r=new Vector();
                    for(int j=0;j<col;++j)
                    {
                        Cell cell=sheet.getCell(j, i);
                        r.add(cell.getContents());
                    }
                    model.addRow(r);
                }
                tbl.setModel(model);
                wordbook.close();
            }
            catch (IOException ex) {
                Logger.getLogger(Kho.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BiffException ex) {
                Logger.getLogger(Kho.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDocEXActionPerformed

    private void cmbMaSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbMaSPFocusLost
        SanPhamBUS khob=new SanPhamBUS();
        khob.DocSP();
        for(SanPham dto: khob.lssp){
            if(dto.getMaSP().equals(cmbMaSP.getSelectedItem().toString()))
            {
                txtTenSP.setText(dto.getTenSP().toString());
                txtMaLoai.setText(dto.getMaLoai().toString());
                break;
            }
        }  
    }//GEN-LAST:event_cmbMaSPFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KhoForm dialog = new KhoForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private int dangthongke=0;
    static int dangdocfile=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btnDocEX;
    private javax.swing.JButton btnLoadDL;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatEX;
    private javax.swing.JComboBox<String> cmbMaSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtGiaXuat;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
