/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.NhanVienBUS;
import BUS.PhanQuyenBUS;
import BUS.TaiKhoanBUS;
import DTO.NhanVien;
import DTO.PhanQuyen;
import DTO.TaiKhoan;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.parser.DTDConstants;

/**
 *
 * @author DELL
 */
public class TKForm extends javax.swing.JDialog {
    DefaultTableModel model;
    TaiKhoanBUS bus;
    /**
     * Creates new form TKForm
     */
    private HomeForm home;
    public TKForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        home=(HomeForm) parent;
        bus=new TaiKhoanBUS();
        bus.DocTaiKhoan();
        model =(DefaultTableModel)tbl.getModel();
        bus.showTable(model);
        loadMaNV();
        loadPhanQuyen();
    }
    
    public void loadMaNV(){
        DefaultComboBoxModel mdsp=new DefaultComboBoxModel();
        NhanVienBUS bus=new NhanVienBUS();
        bus.DocNV();
        for(NhanVien sp: NhanVienBUS.lsk)
            mdsp.addElement(sp.getMaNV());
        cmbMaNV.setModel(mdsp);
    }
    
    public void loadPhanQuyen(){
        DefaultComboBoxModel mdsp=new DefaultComboBoxModel();
        PhanQuyenBUS bus=new PhanQuyenBUS();
        bus.DocPhanQuyen();
        for(PhanQuyen sp: PhanQuyenBUS.lssp)
            mdsp.addElement(sp.getMaQuyen());
        cmbPhanQuyen.setModel(mdsp);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        txtTimKiem = new javax.swing.JTextField();
        btnThem = new javax.swing.JLabel();
        btnXoa = new javax.swing.JLabel();
        btnLoadDL = new javax.swing.JLabel();
        btnSua = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JLabel();
        cmbMaNV = new javax.swing.JComboBox<>();
        cmbPhanQuyen = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        label = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 0));
        jLabel3.setText("ACCOUNT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 0));
        jLabel4.setText("Tìm kiếm theo ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 0));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 20, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 0));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 60, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 153, 0));
        jLabel9.setText("Mã nhân viên");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 153, 0));
        jLabel6.setText("Phân quyền");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 70, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 0));
        jLabel7.setText("Username");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 60, 20));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 150, -1));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, -1));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, -1));

        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimKiemMouseClicked(evt);
            }
        });
        jPanel1.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 150, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 24, 24));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 24, 24));

        btnLoadDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Undo.png"))); // NOI18N
        btnLoadDL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadDLMouseClicked(evt);
            }
        });
        jPanel1.add(btnLoadDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 30, 40));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Modify.png"))); // NOI18N
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 30, 40));

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Find.png"))); // NOI18N
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });
        jPanel1.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 24, 24));

        cmbMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 150, -1));

        cmbPhanQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jPanel1.add(cmbPhanQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 150, -1));

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tbl.setForeground(new java.awt.Color(102, 153, 0));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Phân Quyền", "Mã NV", "User", "Password"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 400, 150));

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 440));

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.png"))); // NOI18N
        btnQuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuayLaiMouseClicked(evt);
            }
        });
        jPanel1.add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 30, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadDLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadDLMouseClicked
        model.setRowCount(0);
        bus.showTable(model);
        txtTimKiem.setText("");
    }//GEN-LAST:event_btnLoadDLMouseClicked

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        String b=txtTimKiem.getText();
        boolean check=false;
        for(int i=0;i<bus.lstk.size();i++){
            if(bus.lstk.get(i).getId().toLowerCase().equals(b.toLowerCase())){
                check=true;
                model.setRowCount(0);
                model.addRow(new Object[]{
                    bus.lstk.get(i).getId(), bus.lstk.get(i).getMaQuyen(), bus.lstk.get(i).getMaNV(), bus.lstk.get(i).getUsername(), bus.lstk.get(i).getPassword()
                });
                break;
            }else if(bus.lstk.get(i).getUsername().toLowerCase().equals(b.toLowerCase())){
                check=true;
                model.setRowCount(0);
                model.addRow(new Object[]{
                    bus.lstk.get(i).getId(), bus.lstk.get(i).getMaQuyen(), bus.lstk.get(i).getMaNV(), bus.lstk.get(i).getUsername(), bus.lstk.get(i).getPassword()
                });
                break;
            }
        }
        if(check==false){
            JOptionPane.showMessageDialog(rootPane, "Không có ID hoặc Username trong bảng nhóe !");
            model.setRowCount(0);
        }
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        TaiKhoan s = new TaiKhoan();
        TaiKhoanBUS bus=new TaiKhoanBUS();
        boolean check=true;
        String b=cmbMaNV.getSelectedItem().toString();
        if(!bus.KiemTraTrungMaNV(b)){
            check=false;
            JOptionPane.showMessageDialog(rootPane, "Trùng  Mã NV mẹ rồi");
        }
        
        String id=txtID.getText();
        if(!bus.KiemTraTrungID(id)){
            check=false;
            JOptionPane.showMessageDialog(rootPane, "Trùng  Mã ID mẹ rồi");
        }
        
        s.setId(id);
        
        PhanQuyenBUS sp=new PhanQuyenBUS();
        sp.DocPhanQuyen();
        String a=cmbPhanQuyen.getSelectedItem().toString();
        if(a.equals("0")){
             check=false;
            JOptionPane.showMessageDialog(rootPane, "Đã có Phần Quyền 0(BOSS).Chọn cái khác đi nhé!");
        }
        s.setMaQuyen(a);
        s.setMaNV(b);
        s.setUsername(txtUser.getText());
        s.setPassword(txtPass.getText());
        
        if(check==true){
            try {
                if(bus.ThemTK(s)==true){
                    bus.showResult(model);
                    JOptionPane.showMessageDialog(rootPane, "Thêm TK thành công");
                    txtID.setText("");
                    txtUser.setText("");
                    txtPass.setText("");
                    txtID.setEnabled(true);
                    txtID.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(TaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Thêm TK thất bại");
            }
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        int row=tbl.getSelectedRow();
        
        boolean check=true;
        if(row == -1){
            JOptionPane.showMessageDialog(rootPane, "Chọn dòng để sủa");
            check=false;
        }
        if(check==true){
            TaiKhoan std = bus.lstk.get(row);
            if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa ?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    bus.xoavitrids(row);
                    bus.XoaTK(std);
                    txtID.setText("");
                    txtUser.setText("");
                    txtPass.setText("");
                    txtID.setEnabled(true);
                    txtID.requestFocus();

                } catch (SQLException ex) {
                    Logger.getLogger(TKForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                model.removeRow(row);
            }
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        TaiKhoan s = new TaiKhoan();
        boolean check=true;
        
        int row=tbl.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(rootPane, "Chọn dòng để sủa");
            check=false;
        }
        String b=cmbMaNV.getSelectedItem().toString();
        if(!bus.KiemTraTrungMaNV(b)){
            check=false;
            JOptionPane.showMessageDialog(rootPane, "Trùng  Mã NV rồi mẹ");
        }
        
        s.setId(txtID.getText());
        PhanQuyenBUS sp=new PhanQuyenBUS();
        sp.DocPhanQuyen();
        String a=cmbPhanQuyen.getSelectedItem().toString();
        if(a.equals("0")){
             check=false;
            JOptionPane.showMessageDialog(rootPane, "Đã có Phần Quyền 0(BOSS).Chọn cái khác đi nhé!");
        }
        s.setMaQuyen(a);
        s.setMaNV(b);
        s.setUsername(txtUser.getText());
        s.setPassword(txtPass.getText());
        
        if(check==true){
            //int row=tbl.getSelectedRow();
            
            try {
                if(bus.SuaTK(s)==true){
                    model.setRowCount(0);
                    bus.DocTaiKhoan();
                    bus.showTable(model);
                    txtID.setText("");
                    txtUser.setText("");
                    txtPass.setText("");
                    txtID.setEnabled(true);
                    txtID.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(TaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
                //JOptionPane.showMessageDialog(rootPane, "Edit thất bại");
            }
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int row=tbl.getSelectedRow();
        txtID.setText(tbl.getModel().getValueAt(row, 0).toString());
        txtID.setEnabled(false);
        cmbPhanQuyen.setSelectedItem(tbl.getModel().getValueAt(row, 1).toString());
        cmbMaNV.setSelectedItem(tbl.getModel().getValueAt(row, 2).toString());
        txtUser.setText(tbl.getModel().getValueAt(row, 3).toString());
        txtPass.setText(tbl.getModel().getValueAt(row, 4).toString());
    }//GEN-LAST:event_tblMouseClicked

    private void btnQuayLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuayLaiMouseClicked
        this.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_btnQuayLaiMouseClicked

    private void txtTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMouseClicked
        txtID.setText("");
        txtUser.setText("");
        txtPass.setText("");
        txtID.setEnabled(true);
    }//GEN-LAST:event_txtTimKiemMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TKForm dialog = new TKForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLoadDL;
    private javax.swing.JLabel btnQuayLai;
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnThem;
    private javax.swing.JLabel btnTimKiem;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JComboBox<String> cmbMaNV;
    private javax.swing.JComboBox<String> cmbPhanQuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
